### ISSUE TITLE
Please explain the usefulness

### ISSUE THREAD

**Issue by pcav** [User111111111/QGIS_Plugins#3]
especially when compared to existing rectangles etc plugin

**Comment by User111111111** [comment]
Hi, this has now been added to the GitHub ReadMe, as follows:

This plugin allows you to create ellipses in QGIS based on minor and major axis diameter widths and a rotation angle, adding additional functionality to that found in previous plugins that only allowed freehand/non-dimensioned drawing of ellipses. The tool can be used for example to map wind turbine separation distances.

The tool will draw the ellipse in the centre of your current QGIS map window, to then be moved as you wish.
